package com.mycompany.main.views;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import com.fazecast.jSerialComm.*;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import javax.swing.JFrame;
import com.mycompany.main.CRC16CCITT;
import com.mycompany.main.HandleSend;
import com.mycompany.main.HandleReceive;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.math.BigInteger;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author labhardware01
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MainForm() {
        initComponents();
        fillDropBoxes();
    }
    
    public File file;
    
    public void fillDropBoxes()
    {
        dropbox.addItem("- -"); int i;
        SerialPort[] commPorts = SerialPort.getCommPorts();
        for(i=0; i<commPorts.length; i++){
            dropbox.addItem(commPorts[i].getSystemPortName());
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainFormPanel = new javax.swing.JPanel();
        textArea = new javax.swing.JTextArea();
        dropbox = new javax.swing.JComboBox<>();
        sendButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        openFile = new javax.swing.JButton();
        inputFilePicker = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        receiveButton = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        scrollPane1 = new java.awt.ScrollPane();
        jLabel3 = new javax.swing.JLabel();
        txtFrames = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        MainFormPanel.setBackground(java.awt.Color.darkGray);
        MainFormPanel.setForeground(new java.awt.Color(255, 255, 255));

        textArea.setColumns(20);
        textArea.setLineWrap(true);
        textArea.setRows(5);
        textArea.setFocusCycleRoot(true);

        dropbox.setBackground(java.awt.Color.gray);
        dropbox.setForeground(new java.awt.Color(255, 255, 255));
        dropbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropboxActionPerformed(evt);
            }
        });

        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        openFile.setText("Open");
        openFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileActionPerformed(evt);
            }
        });

        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("or");

        receiveButton.setText("Receive");
        receiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiveButtonActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Frames: ");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Estatísticas");

        javax.swing.GroupLayout MainFormPanelLayout = new javax.swing.GroupLayout(MainFormPanel);
        MainFormPanel.setLayout(MainFormPanelLayout);
        MainFormPanelLayout.setHorizontalGroup(
            MainFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainFormPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(MainFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainFormPanelLayout.createSequentialGroup()
                        .addComponent(textArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(MainFormPanelLayout.createSequentialGroup()
                        .addGroup(MainFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainFormPanelLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(receiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MainFormPanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1))
                            .addComponent(dropbox, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MainFormPanelLayout.createSequentialGroup()
                                .addComponent(inputFilePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(openFile)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(MainFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainFormPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFrames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainFormPanelLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel2)))
                .addGap(95, 95, 95))
            .addGroup(MainFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MainFormPanelLayout.createSequentialGroup()
                    .addGap(176, 176, 176)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(344, Short.MAX_VALUE)))
        );
        MainFormPanelLayout.setVerticalGroup(
            MainFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainFormPanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(dropbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MainFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textArea, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addGroup(MainFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainFormPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainFormPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addGap(12, 12, 12)
                .addGroup(MainFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openFile, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputFilePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MainFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(MainFormPanelLayout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(MainFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(MainFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtFrames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(MainFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainFormPanelLayout.createSequentialGroup()
                    .addContainerGap(266, Short.MAX_VALUE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(143, 143, 143)))
        );

        textArea.getAccessibleContext().setAccessibleName("textAreaOrigin");
        dropbox.getAccessibleContext().setAccessibleName("dropboxOrigin");
        sendButton.getAccessibleContext().setAccessibleName("sendButton");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if(dropbox.getSelectedItem().toString().length() > 0 && dropbox.getSelectedItem().toString() != "- -") {
            SerialPort commPortOrigin = SerialPort.getCommPort(dropbox.getSelectedItem().toString());
            commPortOrigin.closePort();
        }
    }//GEN-LAST:event_formWindowClosing

    private void receiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiveButtonActionPerformed
        // TODO add your handling code here:
        HandleReceive handleReceive = new HandleReceive(
            dropbox.getSelectedItem().toString(),
            textArea
        );
        handleReceive.startReader();
    }//GEN-LAST:event_receiveButtonActionPerformed

    private void openFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "Selecione apenas seu arquivo",
            "txt", "jpg", "csv", "png", "jspn"
        );
        fileChooser.setFileFilter(filter);

        int chooserReturn = fileChooser.showOpenDialog(null);

        if(chooserReturn == JFileChooser.APPROVE_OPTION) {
            inputFilePicker.setText(fileChooser.getSelectedFile().getAbsolutePath());
        }

        this.file = new File(fileChooser.getSelectedFile().getAbsolutePath());
    }//GEN-LAST:event_openFileActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        String content = "";
        try {
            if(this.file == null) {
                content = textArea.getText();
            } else {
                int r;
                FileInputStream fis = new FileInputStream(this.file);
                while ((r=fis.read())!=-1) {
                    content += (char) r;
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        LinkedHashMap<String,javax.swing.JTextPane> stats = new LinkedHashMap<String,javax.swing.JTextPane>();
        stats.put("frames", txtFrames);
        
        
        HandleSend handleSend = new HandleSend(
            content,
            dropbox.getSelectedItem().toString(),
            this.file == null ? "" : this.file.getName(),
            stats
        );

        handleSend.startTransaction();

        //        SerialPort commPortOrigin = MainForm.openSerialConnection((String) dropboxOrigin.getSelectedItem());
        //        SerialPort commPortTarget = MainForm.openSerialConnection((String) dropboxTarget.getSelectedItem());
        //        this.addListeners(commPortOrigin, commPortTarget);
        //
        //        String content;
        //        //content = MainForm.addScapes(textAreaOrigin.getText());
        //        content = textAreaOrigin.getText();
        //        System.out.println("content: " + content);
        //        int idx = 0;
        //        int offset = 0;
        //        int exit = 0;
        //        int frameLength = 5;
        //        byte origin = 00000001;
        //        byte target = 00000010;
        //        do {
            //            String toFraming;
            //            if(exit == 1) {
                //                toFraming = content.substring(offset, content.length());
                //                byte[] frame = MainForm.framming(toFraming, origin);
                //                System.out.println("\nframming: ");
                //                for (int i = 0; i < frame.length; ++i)
                //                    System.out.print((char)frame[i]);
                //                System.out.println("\n");
                //                this.send(commPortOrigin, frame);
                //                break;
                //            } else {
                //                if(content.length()-1 < frameLength) {
                    //                    toFraming = content.substring(offset, content.length());
                    //                    byte[] frame = MainForm.framming(toFraming, origin);
                    //                    System.out.println("\nframming: ");
                    //                    for (int i = 0; i < frame.length; ++i)
                    //                        System.out.print((char)frame[i]);
                    //                    System.out.println("\n");
                    //                    this.send(commPortOrigin, frame);
                    //                    break;
                    //                }
                //
                //                toFraming = content.substring(offset, offset+frameLength);
                //                offset+=frameLength;
                //                if((content.length() - offset) < content.length()) {
                    //                    exit = 1;
                    //                }
                //
                //
                //            }
            //
            //
            //            byte[] frame = MainForm.framming(toFraming, origin);
            //            System.out.println("\nframming: ");
            //            for (int i = 0; i < frame.length; ++i)
            //                System.out.print((char)frame[i]);
            //            System.out.println("\n");
            //            this.send(commPortOrigin, frame);
            //            idx++;
            //        } while(true);
    }//GEN-LAST:event_sendButtonActionPerformed

    private void dropboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropboxActionPerformed

    private static SerialPort openSerialConnection(String commPort)
    {
        SerialPort port = SerialPort.getCommPort(commPort);
        port.openPort();
        return port;
    }
    
    private void send(SerialPort port, byte[] frame) {
//        byte origin = 00000001;
//        byte target = 00000010;
        
        port.writeBytes(frame, frame.length);
    }
    
    private void addListeners(SerialPort origin, SerialPort target)
    {
        origin.addDataListener(new SerialPortDataListener() {
            @Override
            public int getListeningEvents() { return SerialPort.LISTENING_EVENT_DATA_RECEIVED; }
                @Override
            public void serialEvent(SerialPortEvent event)
            {
                byte[] newData = event.getReceivedData();
                System.out.println("\nReceived data of size: " + newData.length + "\n");
                for (int i = 0; i < newData.length; ++i)
                    System.out.print((byte)newData[i] + " , ");
                System.out.println("\n");
                
//                byte[] ackFrame = MainForm.framming("", target);
//                commPortOrigin.writeBytes(ackFrame, ackFrame.length);
            }
         });
        
        target.addDataListener(new SerialPortDataListener() {
            @Override
            public int getListeningEvents() { return SerialPort.LISTENING_EVENT_DATA_RECEIVED; }
                @Override
            public void serialEvent(SerialPortEvent event)
            {
                byte[] newData = event.getReceivedData();
                System.out.println("\nReceived data of size: " + newData.length + "\n");
                for (int i = 0; i < newData.length; ++i)
                    System.out.print((byte)newData[i]);
                System.out.println("\n");
            }
         });
    }
    

    private static byte[] framming(String content, byte address)
    {
        //char scapeCharacter = '*';
        //char startTextCharacter = '~';
        //char endTextCharacter = '|';joao vitor batistella
        byte startEndFrame = '~';
        byte ack = 1;
        
        String data;
        //data = scapeCharacter + startTextCharacter + content + scapeCharacter + endTextCharacter;
        data = content;
        
        String hexCRC = CRC16CCITT.main(data);
        byte[] crc = MainForm.hexStringToByte(hexCRC);
        
//        System.out.println("\nstartEndFrame: " + startEndFrame);
//        System.out.println("\naddress: " + address);
//        System.out.println("\nack: " + ack);
//        System.out.println("\ndata: " + data);
//        System.out.println("\ncrc[0]: " + crc[0]);
//        System.out.println("\ncrc[1]: " + crc[1]);
//        System.out.println("\nstartEndFrame: " + startEndFrame +"\n\n");
        
        byte[] preFrame = {startEndFrame, address, ack};
        byte[] dataFrame = data.getBytes();
        byte[] postFrame = {crc[0], crc[1], startEndFrame};

        return ByteBuffer.allocate(preFrame.length + dataFrame.length + postFrame.length)
                .put(preFrame)
                .put(dataFrame)
                .put(postFrame)
                .array();
    }
    
    private static byte[] hexStringToByte (String hex)
    {
        int val = Integer.parseInt(hex, 16);

        BigInteger big = BigInteger.valueOf(val);
        byte[] ans = (big.toByteArray());
        return ans;
    }
        
     private static String addScapes(String content) 
    {
        // enquadramento por utilização de byte de inicio e fim de quadro com inserção de caractere de escape
        char scapeCharacter = '*';
        
        int index = 0;
        for(char ch: content.toCharArray()) {
            if(ch == scapeCharacter) {
                content = addChar(content, scapeCharacter, index);
                index +=2;
            } else {
                index++;
            }
            
        }
        
        return content;
    }
    
    public static String addChar(String str, char ch, int position) {
        int len = str.length();
        char[] updatedArr = new char[len + 1];
        str.getChars(0, position, updatedArr, 0);
        updatedArr[position] = ch;
        str.getChars(position, len, updatedArr, position + 1);
        return new String(updatedArr);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainFormPanel;
    private javax.swing.JComboBox<String> dropbox;
    private javax.swing.JTextField inputFilePicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton openFile;
    private javax.swing.JButton receiveButton;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JButton sendButton;
    private javax.swing.JTextArea textArea;
    private javax.swing.JTextPane txtFrames;
    // End of variables declaration//GEN-END:variables
}
